question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "A group of crocodiles are called shrewdness.", "answer": "False"},
    {"text": "Dogs can understand up to 250 hand gestures.", "answer": "True"},
    {"text": "A hair of a polar bear's fur is white.", "answer": "False"},
    {"text": "Limes float, lemons sink.", "answer": "False"},
    {"text": "Bananas are available in colors other than yellow.", "answer": "True"},
    {"text": "Strawberries are not actually berries.", "answer": "True"},
    {"text": "Bananas grow upside down.", "answer": "True"},
    {"text": "M&M stands for Mars and Murrie.", "answer": "True"},
    {"text": "Walt Disney holds the record for the most Oscars.", "answer": "True"},
    {"text": "Cinderella was the first Disney princess .", "answer": "False"},
    {"text": "10,297 balloons were used in the floating sequences for the movie 'Up!'.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Vietnamese is an official language in Canada.", "answer": "False"},
    {"text": "The Japanese car company Toyota was originally established as a textiles manufacturer.",
     "answer": "True"},
    {"text": "The first speeding ticket was in 1896 for driving at 8MPH.", "answer": "True"},
    {"text": "Madonna's real name is Madonna.", "answer": "True"},
    {"text": "The world's Oceans produce over 40% of the oxygen we breath.", "answer": "True"},
    {"text": "Over 90% of sea turtles in the Ocean are found to have consumed plastic.", "answer": "True"},
    {"text": "The life expectancy of a jellyfish is 70 years.", "answer": "False"},
    {"text": "You can sneeze during sleep.", "answer": "False"},
    {"text": "There's a village in the Netherlands with no streets, only canals.", "answer": "True"}
]
